# Data Prep

* View data_prep folder and pipeline file for detailed info
* Parameter to change on new Data: constants.py with cols and paths,
also fail_on_duplcate must be set to true if duplicated values are viewed to be an error (timestamps are always errors).

In [14]:
print("test")

test

In [15]:
from pathlib import Path
import sys

# Ensure the project src/ directory is importable from the notebook.
_cwd = Path.cwd().resolve()
PROJECT_ROOT = next(
    p for p in [_cwd, *_cwd.parents] if (p / "src" / "timeseries_forecast").exists()
)
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from timeseries_forecast.data_prep.raw_data import read_raw_metals_data
from timeseries_forecast.data_prep.pipeline import run_data_pipeline
from timeseries_forecast.data_prep.constants import RawMetalsColumn


# from timeseries_forecast.feature import autoregressive_features
# from timeseries_forecast.eval.eval import evaluate, evaluate_predictions
# from timeseries_forecast.feature.custom_features import add_log_ret_features
# from timeseries_forecast.feature import engineer_features
# from timeseries_forecast.config.feature_config import FeatureConfig
# from timeseries_forecast.data_prep.data_resample import resample_dataframe_with_aggregations

In [16]:
alu_df = read_raw_metals_data("aluminium")
alu_df.Date

0      2024-08-29
1      2024-08-28
2      2024-08-27
3      2024-08-26
4      2024-08-23
          ...
2730   2014-01-07
2731   2014-01-06
2732   2014-01-03
2733   2014-01-02
2734   2014-01-01
Name: Date, Length: 2735, dtype: datetime64[us]

## Cleaning for all metals with same parameters

### Aluminium

In [17]:
alu_df_cleaned = run_data_pipeline(
    read_raw_metals_data("aluminium"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])
alu_df_cleaned

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
⚠ 4 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2020-09-29', '2020-09-30', '2024-07-30', '2024-07-31'], dtype='datetime64[us]', name='RawMetalsColumn.OPEN_TIME', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
⚠ Es gibt 1159 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
⚠ 15 NaN-Werte insgesamt gefunden:
  Vol.: 15 (0.55%)

================================================================================
0-Werte Check
================================================================================
⚠ 32 0-Werte insgesamt gefunden:
  Vol.: 32 (1.17%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,735 Zeilen
  Zu ergänzende Einträge: 1,159
    RawMetalsColumn.VOLUME: 32 Nullwerte → NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1159 → 0 NaN
    Open: 1159 → 0 NaN
    High: 1159 → 0 NaN
    Low: 1159 → 0 NaN
    Vol.: 1206 → 0 NaN
    Change %: 1159 → 0 NaN

  Shape vorher:  (2735, 6)
  Shape nachher: (3894, 6)
✓ Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
✓ Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
✓ Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
✓ Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

             Close        Open        High         Low         Vol.   Mode
2014-01-01  110.10  110.000000  110.700000  109.900000   450.000000  Train
2014-01-02  111.20  110.550000  112.200000  110.450000  4720.000000  Train
2014-01-03  109.20  110.900000  111.100000  109.050000  4520.000000  Train
2014-01-04  109.35  110.433333  110.650000  108.733333  4333.333333  Train
2014-01-05  109.50  109.966667  110.200000  108.416667  4146.666667  Train
...            ...         ...         ...         ...          ...    ...
2024-08-25  229.60  229.450000  232.433333  227.483333  1236.666667   Test
2024-08-26  229.50  230.850000  233.500000  228.850000   510.000000   Test
2024-08-27  231.55  229.000000  233.000000  228.200000    60.000000   Test
2024-08-28  232.05  233.400000  233.400000  231.400000    35.000000   Test
2024-08-29  228.30  230.150000  230.150000  227.500000    10.000000   Test

[3894 rows x 6 columns]

In [18]:
# alu_df_cleaned.loc["25-08-2024"]

### Copper

In [19]:
copper_df_cleaned = run_data_pipeline(
    read_raw_metals_data("copper"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
⚠ Es gibt 1136 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
⚠ 20 NaN-Werte insgesamt gefunden:
  Vol.: 20 (0.73%)

================================================================================
0-Werte Check
================================================================================
⚠ 5 0-Werte insgesamt gefunden:
  Vol.: 5 (0.18%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,758 Zeilen
  Zu ergänzende Einträge: 1,136
    RawMetalsColumn.VOLUME: 5 Nullwerte → NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1136 → 0 NaN
    Open: 1136 → 0 NaN
    High: 1136 → 0 NaN
    Low: 1136 → 0 NaN
    Vol.: 1161 → 0 NaN
    Change %: 1136 → 0 NaN

  Shape vorher:  (2758, 6)
  Shape nachher: (3894, 6)
✓ Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
✓ Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
✓ Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
✓ Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

### gold

In [20]:
gold_df_cleaned = run_data_pipeline(
    read_raw_metals_data("gold"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
⚠ Es gibt 1135 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
⚠ 22 NaN-Werte insgesamt gefunden:
  Vol.: 22 (0.80%)

================================================================================
0-Werte Check
================================================================================
⚠ 7 0-Werte insgesamt gefunden:
  Vol.: 7 (0.25%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,895 Einträge
  Aktueller DataFrame:    2,760 Zeilen
  Zu ergänzende Einträge: 1,135
    RawMetalsColumn.VOLUME: 7 Nullwerte → NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1135 → 0 NaN
    Open: 1135 → 0 NaN
    High: 1135 → 0 NaN
    Low: 1135 → 0 NaN
    Vol.: 1164 → 0 NaN
    Change %: 1135 → 0 NaN

  Shape vorher:  (2760, 6)
  Shape nachher: (3895, 6)
✓ Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
✓ Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
✓ Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
✓ Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-30 00:00:00 | rows=973

### lead

In [21]:
lead_df_cleaned = run_data_pipeline(
    read_raw_metals_data("lead"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
    fail_on_row_duplicates=False,
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
⚠ 6 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2023-03-29', '2023-03-30', '2023-07-27', '2023-07-28',
               '2024-02-26'],
              dtype='datetime64[us]', name='RawMetalsColumn.OPEN_TIME', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
⚠ Es gibt 1137 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
⚠ 31 NaN-Werte insgesamt gefunden:
  Vol.: 31 (1.12%)

================================================================================
0-Werte Check
================================================================================
⚠ 45 0-Werte insgesamt gefunden:
  Vol.: 45 (1.63%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,757 Zeilen
  Zu ergänzende Einträge: 1,137
    RawMetalsColumn.VOLUME: 45 Nullwerte → NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1137 → 0 NaN
    Open: 1137 → 0 NaN
    High: 1137 → 0 NaN
    Low: 1137 → 0 NaN
    Vol.: 1213 → 0 NaN
    Change %: 1137 → 0 NaN

  Shape vorher:  (2757, 6)
  Shape nachher: (3894, 6)
✓ Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
⚠ 2 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2023-03-29', '2023-03-30'], dtype='datetime64[us]', freq='D')

================================================================================
Fehlende Werte Check
================================================================================
✓ Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
✓ Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
✓ Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

### nickel

In [25]:
nickel_df_cleaned = run_data_pipeline(
    read_raw_metals_data("nickel"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[
        RawMetalsColumn.VOLUME,
        RawMetalsColumn.OPEN,
        RawMetalsColumn.HIGH,
        RawMetalsColumn.LOW,
    ],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])
nickel_df_cleaned

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
⚠ 21 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2022-05-27', '2022-05-30', '2022-05-31', '2022-06-02',
               '2022-06-03'],
              dtype='datetime64[us]', name='RawMetalsColumn.OPEN_TIME', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
⚠ Es gibt 1139 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
⚠ 580 NaN-Werte insgesamt gefunden:
  Vol.: 580 (21.05%)

================================================================================
0-Werte Check
================================================================================
⚠ 40 0-Werte insgesamt gefunden:
  Open: 1 (0.04%)
  High: 1 (0.04%)
  Low: 1 (0.04%)
  Vol.: 37 (1.34%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,755 Zeilen
  Zu ergänzende Einträge: 1,139
    RawMetalsColumn.VOLUME: 37 Nullwerte → NaN ersetzt
    RawMetalsColumn.OPEN: 1 Nullwerte → NaN ersetzt
    RawMetalsColumn.HIGH: 1 Nullwerte → NaN ersetzt
    RawMetalsColumn.LOW: 1 Nullwerte → NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1139 → 0 NaN
    Open: 1140 → 0 NaN
    High: 1140 → 0 NaN
    Low: 1140 → 0 NaN
    Vol.: 1756 → 0 NaN
    Change %: 1139 → 0 NaN

  Shape vorher:  (2755, 6)
  Shape nachher: (3894, 6)
✓ Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
⚠ 23 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2022-05-27', '2022-05-28', '2022-05-29', '2022-05-30',
               '2022-05-31'],
              dtype='datetime64[us]', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
✓ Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
✓ Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
✓ Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

,Close,Open,High,Low,Vol.,Mode
2014-01-01,866.100000,867.000000,869.900000,863.000000,2430.000000,Train
2014-01-02,875.200000,869.900000,880.500000,862.600000,20390.000000,Train
2014-01-03,865.100000,873.100000,875.000000,863.500000,13910.000000,Train
2014-01-04,865.100000,865.100000,865.100000,865.100000,16163.333333,Train
2014-01-05,858.100000,866.300000,867.200000,856.100000,18416.666667,Train
...,...,...,...,...,...,...
2024-08-25,1415.833333,1415.833333,1415.833333,1415.833333,20.000000,Test
2024-08-26,1420.400000,1420.400000,1420.400000,1420.400000,20.000000,Test
2024-08-27,1420.400000,1420.400000,1420.400000,1420.400000,20.000000,Test
2024-08-28,1438.000000,1438.000000,1438.000000,1438.000000,20.000000,Test
2024-08-29,1427.500000,1427.500000,1427.500000,1427.500000,20.000000,Test

### silver

In [26]:
silver_df_cleaned = run_data_pipeline(
    read_raw_metals_data("silver"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[
        RawMetalsColumn.VOLUME,
        RawMetalsColumn.OPEN,
        RawMetalsColumn.HIGH,
        RawMetalsColumn.LOW,
    ],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
⚠ Es gibt 1136 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
⚠ 18 NaN-Werte insgesamt gefunden:
  Vol.: 18 (0.65%)

================================================================================
0-Werte Check
================================================================================
⚠ 5 0-Werte insgesamt gefunden:
  Vol.: 5 (0.18%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,895 Einträge
  Aktueller DataFrame:    2,759 Zeilen
  Zu ergänzende Einträge: 1,136
    RawMetalsColumn.VOLUME: 5 Nullwerte → NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1136 → 0 NaN
    Open: 1136 → 0 NaN
    High: 1136 → 0 NaN
    Low: 1136 → 0 NaN
    Vol.: 1159 → 0 NaN
    Change %: 1136 → 0 NaN

  Shape vorher:  (2759, 6)
  Shape nachher: (3895, 6)
✓ Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
✓ Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
✓ Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
✓ Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-30 00:00:00 | rows=973

### zinc

In [27]:
zinc_df_cleaned = run_data_pipeline(
    read_raw_metals_data("zinc"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
⚠ Es gibt 1137 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
⚠ 19 NaN-Werte insgesamt gefunden:
  Vol.: 19 (0.69%)

================================================================================
0-Werte Check
================================================================================
⚠ 13 0-Werte insgesamt gefunden:
  Vol.: 13 (0.47%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,895 Einträge
  Aktueller DataFrame:    2,758 Zeilen
  Zu ergänzende Einträge: 1,137
    RawMetalsColumn.VOLUME: 13 Nullwerte → NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1137 → 0 NaN
    Open: 1137 → 0 NaN
    High: 1137 → 0 NaN
    Low: 1137 → 0 NaN
    Vol.: 1169 → 0 NaN
    Change %: 1137 → 0 NaN

  Shape vorher:  (2758, 6)
  Shape nachher: (3895, 6)
✓ Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
✓ Keine doppelten Zeitstempel im Index
✓ Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
✓ Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
✓ Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
✓ Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-30 00:00:00 | rows=973

### Save Dataset

In [ ]:
from pathlib import Path

cleaned_dir = PROJECT_ROOT / "data" / "cleaned"
cleaned_dir.mkdir(parents=True, exist_ok=True)

output_path = cleaned_dir / "metals_aluminium_cleaned.csv"
alu_df_cleaned.to_csv(output_path, index=True)

## hier möglich alle DataFrames zu speichern, z.B. mit Schleife
# Data cleaning kann aber auch ein vor jedem notebook gemacht werden
# output_path = cleaned_dir / "metals_gold_cleaned.csv"
# gold.to_csv(output_path, index=True)
# .....

print(f"Saved cleaned dataframe to: {output_path}")