# Data Prep

* View data_prep folder and pipeline file for detailed info
* Parameter to change on new Data: constants.py with cols and paths,
also fail_on_duplcate must be set to true if duplicated values are viewed to be an error (timestamps are always errors).

In [9]:
print("test")

test

In [10]:
from pathlib import Path
import sys

# Ensure the project src/ directory is importable from the notebook.
_cwd = Path.cwd().resolve()
PROJECT_ROOT = next(
    p for p in [_cwd, *_cwd.parents] if (p / "src" / "timeseries_forecast").exists()
)
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from timeseries_forecast.data_prep.raw_data import read_raw_metals_data
from timeseries_forecast.data_prep.pipeline import run_data_pipeline
from timeseries_forecast.data_prep.data_merge import merge_all_raw_data
from timeseries_forecast.data_prep.constants import RawMetalsColumn

# from timeseries_forecast.feature import autoregressive_features
# from timeseries_forecast.eval.eval import evaluate, evaluate_predictions
# from timeseries_forecast.feature.custom_features import add_log_ret_features
# from timeseries_forecast.feature import engineer_features
# from timeseries_forecast.config.feature_config import FeatureConfig
# from timeseries_forecast.data_prep.data_resample import resample_dataframe_with_aggregations

In [11]:
alu_df = read_raw_metals_data("aluminium")
alu_df.Date

0      2024-08-29
1      2024-08-28
2      2024-08-27
3      2024-08-26
4      2024-08-23
          ...
2730   2014-01-07
2731   2014-01-06
2732   2014-01-03
2733   2014-01-02
2734   2014-01-01
Name: Date, Length: 2735, dtype: datetime64[us]

## Cleaning for all metals with same parameters

### Aluminium

In [12]:
aluminium_df_cleaned = run_data_pipeline(
    read_raw_metals_data("aluminium"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])
aluminium_df_cleaned

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
WARN: 4 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2020-09-29', '2020-09-30', '2024-07-30', '2024-07-31'], dtype='datetime64[us]', name='RawMetalsColumn.OPEN_TIME', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1159 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 15 NaN-Werte insgesamt gefunden:
  Vol.: 15 (0.55%)

================================================================================
0-Werte Check
================================================================================
WARN: 32 0-Werte insgesamt gefunden:
  Vol.: 32 (1.17%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,735 Zeilen
  Zu ergänzende Einträge: 1,159
    RawMetalsColumn.VOLUME: 32 Nullwerte -> NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1159 -> 0 NaN
    Open: 1159 -> 0 NaN
    High: 1159 -> 0 NaN
    Low: 1159 -> 0 NaN
    Vol.: 1206 -> 0 NaN
    Change %: 1159 -> 0 NaN

  Shape vorher:  (2735, 6)
  Shape nachher: (3894, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

             Close        Open        High         Low         Vol.   Mode
2014-01-01  110.10  110.000000  110.700000  109.900000   450.000000  Train
2014-01-02  111.20  110.550000  112.200000  110.450000  4720.000000  Train
2014-01-03  109.20  110.900000  111.100000  109.050000  4520.000000  Train
2014-01-04  109.35  110.433333  110.650000  108.733333  4333.333333  Train
2014-01-05  109.50  109.966667  110.200000  108.416667  4146.666667  Train
...            ...         ...         ...         ...          ...    ...
2024-08-25  229.60  229.450000  232.433333  227.483333  1236.666667   Test
2024-08-26  229.50  230.850000  233.500000  228.850000   510.000000   Test
2024-08-27  231.55  229.000000  233.000000  228.200000    60.000000   Test
2024-08-28  232.05  233.400000  233.400000  231.400000    35.000000   Test
2024-08-29  228.30  230.150000  230.150000  227.500000    10.000000   Test

[3894 rows x 6 columns]

In [13]:
# alu_df_cleaned.loc["25-08-2024"]

### Copper

In [14]:
copper_df_cleaned = run_data_pipeline(
    read_raw_metals_data("copper"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1136 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 20 NaN-Werte insgesamt gefunden:
  Vol.: 20 (0.73%)

================================================================================
0-Werte Check
================================================================================
WARN: 5 0-Werte insgesamt gefunden:
  Vol.: 5 (0.18%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,758 Zeilen
  Zu ergänzende Einträge: 1,136
    RawMetalsColumn.VOLUME: 5 Nullwerte -> NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1136 -> 0 NaN
    Open: 1136 -> 0 NaN
    High: 1136 -> 0 NaN
    Low: 1136 -> 0 NaN
    Vol.: 1161 -> 0 NaN
    Change %: 1136 -> 0 NaN

  Shape vorher:  (2758, 6)
  Shape nachher: (3894, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

### gold

In [15]:
gold_df_cleaned = run_data_pipeline(
    read_raw_metals_data("gold"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1135 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 22 NaN-Werte insgesamt gefunden:
  Vol.: 22 (0.80%)

================================================================================
0-Werte Check
================================================================================
WARN: 7 0-Werte insgesamt gefunden:
  Vol.: 7 (0.25%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,895 Einträge
  Aktueller DataFrame:    2,760 Zeilen
  Zu ergänzende Einträge: 1,135
    RawMetalsColumn.VOLUME: 7 Nullwerte -> NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1135 -> 0 NaN
    Open: 1135 -> 0 NaN
    High: 1135 -> 0 NaN
    Low: 1135 -> 0 NaN
    Vol.: 1164 -> 0 NaN
    Change %: 1135 -> 0 NaN

  Shape vorher:  (2760, 6)
  Shape nachher: (3895, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-30 00:00:00 | rows=973

### lead

In [16]:
lead_df_cleaned = run_data_pipeline(
    read_raw_metals_data("lead"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
    fail_on_row_duplicates=False,
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
WARN: 6 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2023-03-29', '2023-03-30', '2023-07-27', '2023-07-28',
               '2024-02-26'],
              dtype='datetime64[us]', name='RawMetalsColumn.OPEN_TIME', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1137 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 31 NaN-Werte insgesamt gefunden:
  Vol.: 31 (1.12%)

================================================================================
0-Werte Check
================================================================================
WARN: 45 0-Werte insgesamt gefunden:
  Vol.: 45 (1.63%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,757 Zeilen
  Zu ergänzende Einträge: 1,137
    RawMetalsColumn.VOLUME: 45 Nullwerte -> NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1137 -> 0 NaN
    Open: 1137 -> 0 NaN
    High: 1137 -> 0 NaN
    Low: 1137 -> 0 NaN
    Vol.: 1213 -> 0 NaN
    Change %: 1137 -> 0 NaN

  Shape vorher:  (2757, 6)
  Shape nachher: (3894, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
WARN: 2 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2023-03-29', '2023-03-30'], dtype='datetime64[us]', freq='D')

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

### nickel

In [17]:
nickel_df_cleaned = run_data_pipeline(
    read_raw_metals_data("nickel"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[
        RawMetalsColumn.VOLUME,
        RawMetalsColumn.OPEN,
        RawMetalsColumn.HIGH,
        RawMetalsColumn.LOW,
    ],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])
nickel_df_cleaned

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
WARN: 21 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2022-05-27', '2022-05-30', '2022-05-31', '2022-06-02',
               '2022-06-03'],
              dtype='datetime64[us]', name='RawMetalsColumn.OPEN_TIME', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1139 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 580 NaN-Werte insgesamt gefunden:
  Vol.: 580 (21.05%)

================================================================================
0-Werte Check
================================================================================
WARN: 40 0-Werte insgesamt gefunden:
  Open: 1 (0.04%)
  High: 1 (0.04%)
  Low: 1 (0.04%)
  Vol.: 37 (1.34%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,894 Einträge
  Aktueller DataFrame:    2,755 Zeilen
  Zu ergänzende Einträge: 1,139
    RawMetalsColumn.VOLUME: 37 Nullwerte -> NaN ersetzt
    RawMetalsColumn.OPEN: 1 Nullwerte -> NaN ersetzt
    RawMetalsColumn.HIGH: 1 Nullwerte -> NaN ersetzt
    RawMetalsColumn.LOW: 1 Nullwerte -> NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1139 -> 0 NaN
    Open: 1140 -> 0 NaN
    High: 1140 -> 0 NaN
    Low: 1140 -> 0 NaN
    Vol.: 1756 -> 0 NaN
    Change %: 1139 -> 0 NaN

  Shape vorher:  (2755, 6)
  Shape nachher: (3894, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
WARN: 23 Zeilen sind doppelt (identischer Inhalt)
  Beispiele (erste 5 Timestamps):
DatetimeIndex(['2022-05-27', '2022-05-28', '2022-05-29', '2022-05-30',
               '2022-05-31'],
              dtype='datetime64[us]', freq=None)

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-29 00:00:00 | rows=972

,Close,Open,High,Low,Vol.,Mode
2014-01-01,866.100000,867.000000,869.900000,863.000000,2430.000000,Train
2014-01-02,875.200000,869.900000,880.500000,862.600000,20390.000000,Train
2014-01-03,865.100000,873.100000,875.000000,863.500000,13910.000000,Train
2014-01-04,865.100000,865.100000,865.100000,865.100000,16163.333333,Train
2014-01-05,858.100000,866.300000,867.200000,856.100000,18416.666667,Train
...,...,...,...,...,...,...
2024-08-25,1415.833333,1415.833333,1415.833333,1415.833333,20.000000,Test
2024-08-26,1420.400000,1420.400000,1420.400000,1420.400000,20.000000,Test
2024-08-27,1420.400000,1420.400000,1420.400000,1420.400000,20.000000,Test
2024-08-28,1438.000000,1438.000000,1438.000000,1438.000000,20.000000,Test
2024-08-29,1427.500000,1427.500000,1427.500000,1427.500000,20.000000,Test

### silver

In [18]:
silver_df_cleaned = run_data_pipeline(
    read_raw_metals_data("silver"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[
        RawMetalsColumn.VOLUME,
        RawMetalsColumn.OPEN,
        RawMetalsColumn.HIGH,
        RawMetalsColumn.LOW,
    ],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1136 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 18 NaN-Werte insgesamt gefunden:
  Vol.: 18 (0.65%)

================================================================================
0-Werte Check
================================================================================
WARN: 5 0-Werte insgesamt gefunden:
  Vol.: 5 (0.18%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,895 Einträge
  Aktueller DataFrame:    2,759 Zeilen
  Zu ergänzende Einträge: 1,136
    RawMetalsColumn.VOLUME: 5 Nullwerte -> NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1136 -> 0 NaN
    Open: 1136 -> 0 NaN
    High: 1136 -> 0 NaN
    Low: 1136 -> 0 NaN
    Vol.: 1159 -> 0 NaN
    Change %: 1136 -> 0 NaN

  Shape vorher:  (2759, 6)
  Shape nachher: (3895, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-30 00:00:00 | rows=973

### zinc

In [19]:
zinc_df_cleaned = run_data_pipeline(
    read_raw_metals_data("zinc"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[RawMetalsColumn.PCT_CHANGE],
    zero_as_nan_cols=[RawMetalsColumn.VOLUME],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE])

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1137 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 19 NaN-Werte insgesamt gefunden:
  Vol.: 19 (0.69%)

================================================================================
0-Werte Check
================================================================================
WARN: 13 0-Werte insgesamt gefunden:
  Vol.: 13 (0.47%)

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 3,895 Einträge
  Aktueller DataFrame:    2,758 Zeilen
  Zu ergänzende Einträge: 1,137
    RawMetalsColumn.VOLUME: 13 Nullwerte -> NaN ersetzt

  Interpoliere 6 numerische Spalten:
    Price: 1137 -> 0 NaN
    Open: 1137 -> 0 NaN
    High: 1137 -> 0 NaN
    Low: 1137 -> 0 NaN
    Vol.: 1169 -> 0 NaN
    Change %: 1137 -> 0 NaN

  Shape vorher:  (2758, 6)
  Shape nachher: (3895, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2014-01-01 00:00:00 -> 2019-12-31 00:00:00 | rows=2191
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2024-08-30 00:00:00 | rows=973

## SP 500

In [20]:
sp500_df_cleaned = run_data_pipeline(
    read_raw_metals_data("sp500"),
    timestamp_column=RawMetalsColumn.OPEN_TIME,
    data_freq="D",
    split_train_end="2019-12-31",
    split_val_end="2021-12-31",
    zero_value_ignore_cols=[
        RawMetalsColumn.PCT_CHANGE,
        RawMetalsColumn.VOLUME],
    zero_as_nan_cols=[
        RawMetalsColumn.OPEN,
        RawMetalsColumn.HIGH,
        RawMetalsColumn.LOW,
    ],
).rename(columns={RawMetalsColumn.PRICE: "Close"}).drop(columns=[RawMetalsColumn.PCT_CHANGE]).drop(columns=[RawMetalsColumn.VOLUME])

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
WARN: Es gibt 1602 Lücken in der Zeitreihe (erwartete Frequenz: D).

================================================================================
NaN-Check
================================================================================
WARN: 3540 NaN-Werte insgesamt gefunden:
  Vol.: 3540 (99.97%)

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!

================================================================================
Data Cleaning – Interpolation von Missing Values und Nullwerten
================================================================================

  Vollständiger Zeitindex: 5,143 Einträge
  Aktueller DataFrame:    3,541 Zeilen
  Zu ergänzende Einträge: 1,602

  Interpoliere 6 numerische Spalten:
    Price: 1602 -> 0 NaN
    Open: 1602 -> 0 NaN
    High: 1602 -> 0 NaN
    Low: 1602 -> 0 NaN
    Vol.: 5142 -> 0 NaN
    Change %: 1602 -> 0 NaN

  Shape vorher:  (3541, 6)
  Shape nachher: (5143, 6)
OK: Interpolation abgeschlossen!

================================================================================
Duplikat-Check
================================================================================
OK: Keine doppelten Zeitstempel im Index
OK: Keine identischen Zeilenduplikate gefunden

================================================================================
Fehlende Werte Check
================================================================================
OK: Keine Lücken in der Zeitreihe gefunden (Frequenz: D).

================================================================================
NaN-Check
================================================================================
OK: Keine NaN-Werte gefunden!

================================================================================
0-Werte Check
================================================================================
OK: Keine 0-Werte gefunden!
Splits:
  Train: 2012-03-26 00:00:00 -> 2019-12-31 00:00:00 | rows=2837
  Val:   2020-01-01 00:00:00 -> 2021-12-31 00:00:00 | rows=731
  Test:  2022-01-01 00:00:00 -> 2026-04-24 00:00:00 | rows=1575

## Merge

In [21]:
merged_df = merge_all_raw_data(
    aluminium_df_cleaned=aluminium_df_cleaned,
    copper_df_cleaned=copper_df_cleaned,
    gold_df_cleaned=gold_df_cleaned,
    lead_df_cleaned=lead_df_cleaned,
    nickel_df_cleaned=nickel_df_cleaned,
    silver_df_cleaned=silver_df_cleaned,
    zinc_df_cleaned=zinc_df_cleaned,
    sp500_df_cleaned=sp500_df_cleaned,
)

In [22]:
df = merged_df.copy()
df.columns

Index(['ALU_Close', 'ALU_Open', 'ALU_High', 'ALU_Low', 'ALU_Vol.', 'ALU_Mode',
       'COPPER_Close', 'COPPER_Open', 'COPPER_High', 'COPPER_Low',
       'COPPER_Vol.', 'COPPER_Mode', 'GOLD_Close', 'GOLD_Open', 'GOLD_High',
       'GOLD_Low', 'GOLD_Vol.', 'GOLD_Mode', 'LEAD_Close', 'LEAD_Open',
       'LEAD_High', 'LEAD_Low', 'LEAD_Vol.', 'LEAD_Mode', 'NICKEL_Close',
       'NICKEL_Open', 'NICKEL_High', 'NICKEL_Low', 'NICKEL_Vol.',
       'NICKEL_Mode', 'SILVER_Close', 'SILVER_Open', 'SILVER_High',
       'SILVER_Low', 'SILVER_Vol.', 'SILVER_Mode', 'ZINC_Close', 'ZINC_Open',
       'ZINC_High', 'ZINC_Low', 'ZINC_Vol.', 'ZINC_Mode', 'SP500_Close',
       'SP500_Open', 'SP500_High', 'SP500_Low', 'SP500_Mode'],
      dtype='str')

In [23]:
# # Test the function
# frequency_resample = '1h'

# resampled = resample_dataframe_with_aggregations(df, frequency_resample)
# print(f"Original shape: {df.shape}")
# print(f"Resampled {frequency_resample} shape: {resampled.shape}")
# print(f"\nFirst few rows of resampled data:")
# print(resampled.head())

In [24]:
# df = resampled.copy()

In [25]:
# models = [
#     # RandomForestRegressor(random_state=42),
#     # DecisionTreeRegressor(random_state=42),
#     SVR(),
#     LinearSVR(random_state=42),
#     LGBMRegressor(random_state=42),
#     XGBRegressor(random_state=42),
#     LinearRegression(),
#     KNeighborsRegressor()
# ]

In [26]:
# fügt eine type spalte als label (target) hinzu
# macht die timestamp spalte explizit, damit man daraus infos extrahieren kann

df["type"] = "Aluminium"
df["timestamp"] = df.index

In [27]:
# add log ret features
from timeseries_forecast.feature.custom_features import add_log_ret_features

feature_df, feature_name_btc_log_ret = add_log_ret_features(df, "ALU_Close")
#feature_df, feature_name_eth_log_ret = add_log_ret_features(feature_df, "ETH_Close")

In [28]:
# feature_df.columns

In [29]:
#without mode

numeric_feature_columns = ['ALU_Close', 'ALU_Open', 'ALU_High', 'ALU_Low',
       'ALU_Vol.', 'COPPER_Close', 'COPPER_Open',
       'COPPER_High', 'COPPER_Low', 'COPPER_Vol.', 'GOLD_Close',
       'GOLD_Open', 'GOLD_High', 'GOLD_Low', 'GOLD_Vol.',
       'LEAD_Close', 'LEAD_Open', 'LEAD_High', 'LEAD_Low', 'LEAD_Vol.',
       'NICKEL_Close', 'NICKEL_Open', 'NICKEL_High', 'NICKEL_Low',
       'NICKEL_Vol.', 'SILVER_Close', 'SILVER_Open',
       'SILVER_High', 'SILVER_Low', 'SILVER_Vol.', 'ZINC_Close',
       'ZINC_Open', 'ZINC_High', 'ZINC_Low', 'ZINC_Vol.', 'SP500_Close',
       'SP500_Open', 'SP500_High', 'SP500_Low'
       ]

# Feature Engineering

### Lag Features

lag features sind die Features, die die Werte von den Vorherigen Zeilen annehemn, hier wird durch lag_window_len festgelegt, wie weit dies in die Zukunft gelegt werden soll. Zb bei einer täglichen Frequency und bei einer lag_window_len = 12, werden für jeden Wert die Werte der letzten 12 Tage gespeichert.

In [59]:
import timeseries_forecast.feature.engineer_features as engineer_features
lag_window_len = 12

lag = list(range(1, lag_window_len + 1))

features = []
for column in numeric_feature_columns:
    features.append(
        LaggingFeatures
        (
            column=column, 
            lags=lag,
         
        )
    )

### Rolling Features

In [60]:
for column in numeric_feature_columns:
    features.append(
        RollingFeatures
        (
            column=column, 
            rolls=[3, 6, 12],
            agg_funcs=["mean", "std", "min", "max"]
        )
    )

### Temporal Features

In [61]:
# features.append(
#     engineer_features.TemporalFeatures
#     (
#         column="timestamp",
#         frequency="24h"
#     )
# )

# print("✓ Temporal features added")

### Fourier Features (Seasonal Patterns)

In [62]:
# # Add Fourier features for capturing seasonal patterns in the data
# # These are useful for recurring patterns like yearly seasonality
# features.append(
#     engineer_features.FourierFeatures
#     (
#         column="timestamp",
#         max_value=365,  # Yearly seasonality (365 daily observations per year)
#         n_fourier_terms=4  # 4 sine and 4 cosine terms
#     )
# )

# print("✓ Fourier features added (yearly seasonality with 4 terms)")

# Feature Definition

In [63]:
from timeseries_forecast.config.feature_config import FeatureConfig 
from timeseries_forecast.data_prep.data_resample import resample_dataframe_with_aggregations
import pandas as pd

def define_features(df: pd.DataFrame, forecast_horizon: int):
    feature_engineer = engineer_features.FeatureEngineeringConfig(features=features)
    features_df, added_features = feature_engineer.create_features(df, forecast_horizon)

    #this line adds contemp eth log return as feature
    #added_features.extend(feature_name_eth_log_ret)

    feat_config = FeatureConfig(
        date="timestamp",
        target="ALU_Close",
        continuous_features=added_features,
        categorical_features=[],
        boolean_features=[],
        index_cols=["type","timestamp"],
        exogenous_features=[],
    )

    return feat_config, features_df

In [64]:
#forecast horizon defined here 
feature_config, features_df = define_features(feature_df, forecast_horizon=1)

/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:39: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**col_dict)
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))
/home/jjj/Documents/fpp/src/timeseries_forecast/feature/autoregressive_features.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.assign(**rolling_df.to_dict("list"))

In [65]:
df_train = features_df[features_df["ALU_Mode"] == "Train"].dropna()
df_val = features_df[features_df["ALU_Mode"] == "Val"]
df_test = features_df[features_df["ALU_Mode"] == "Test"]

In [66]:
train_features, train_target, _ = feature_config.get_X_y(df_train)
val_features, val_target, _ = feature_config.get_X_y(df_val)
test_features, test_target, _ = feature_config.get_X_y(df_test)

Hier würde jetzt das Training für die Modelle etc kommen

In [74]:
# zB so würde ein model trainiert und evaluiert werden
from sklearn.ensemble import RandomForestRegressor

from timeseries_forecast.eval.eval import evaluate

model = RandomForestRegressor()

model.fit(train_features, train_target)
val_preds = model.predict(val_features)
val_eval_df = val_target.copy()
val_eval_df["pred"] = val_preds

/home/jjj/Documents/fpp/.venv/lib/python3.11/site-packages/sklearn/base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [76]:
val_eval_df

                       ALU_Close        pred
type      timestamp
Aluminium 2020-01-01  137.200000  137.261500
          2020-01-02  137.650000  137.356500
          2020-01-03  139.900000  137.599750
          2020-01-04  140.416667  139.954333
          2020-01-05  140.933333  140.430000
...                          ...         ...
          2021-12-27  227.600000  156.139500
          2021-12-28  227.200000  156.040333
          2021-12-29  226.150000  155.593333
          2021-12-30  224.600000  155.876500
          2021-12-31  223.400000  156.026167

[731 rows x 2 columns]

In [79]:
val_score = evaluate(val_eval_df, target_col="ALU_Close", y_pred_col="pred", do_calculate_directed_accuracy=True)
test_preds = model.predict(test_features)
test_eval_df = test_target.copy()
test_eval_df["pred"] = test_preds
test_score = evaluate(test_eval_df, target_col="ALU_Close", y_pred_col="pred", do_calculate_directed_accuracy=True)
print(test_score)

EvaluationResults(mae=62.16780401234569, rmse=65.8503687017558, mse=4336.27105815718, r2=-8.048691299103266, smape=np.float64(0.16670990650474132), smape_total=np.float64(0.1667099065047413), forecast_bias=np.float64(-62.16780401234569), accuracy=np.float64(83.32900934952588), accuracy_total=np.float64(83.32900934952588), directed_accuracy=np.float64(1.0))

EvaluationResults(mae=62.16780401234569, rmse=65.8503687017558, mse=4336.27105815718, r2=-8.048691299103266, smape=np.float64(0.16670990650474132), smape_total=np.float64(0.1667099065047413), forecast_bias=np.float64(-62.16780401234569), accuracy=np.float64(83.32900934952588), accuracy_total=np.float64(83.32900934952588), directed_accuracy=np.float64(1.0))

explain these evaluation resulats of a random forrest regressor

These are evaluation metrics for your **Random Forest Regressor**. Some metrics suggest the model is doing reasonably well, while others indicate serious problems — especially the **negative R²**.

Here’s what each metric means and how to interpret your results.

---

# Overall Interpretation

Your model appears to:

* Predict the **direction/trend** correctly (`directed_accuracy = 1.0`)
* Have decent percentage-based accuracy (`~83%`)
* But perform **very poorly compared to a baseline mean predictor** (`R² = -8.05`)

That combination usually means:

* The model captures movement direction,
* but misses the actual values badly,
* or there is a scaling / leakage / evaluation issue.

---

# Metric-by-Metric Explanation

## 1. MAE (Mean Absolute Error)

[
MAE = \frac{1}{n}\sum |y_i - \hat{y}_i|
]

MAE = \frac{1}{n}\sum_{i=1}^{n}|y_i-\hat{y}_i|

### Your Result

```python
mae = 62.17
```

### Meaning

On average, your predictions are off by about **62 units**.

Example:

* True value = 500
* Prediction = 438
* Error ≈ 62

### Interpretation

Whether this is good or bad depends entirely on the scale of your target variable.

* If targets are around:

  * `100` → terrible
  * `10,000` → very good

---

# 2. MSE (Mean Squared Error)

[
MSE = \frac{1}{n}\sum (y_i - \hat{y}_i)^2
]

MSE = \frac{1}{n}\sum_{i=1}^{n}(y_i-\hat{y}_i)^2

### Your Result

```python
mse = 4336.27
```

### Meaning

This squares the errors before averaging.

Large mistakes are punished heavily.

### Interpretation

Because errors are squared:

* a few very bad predictions can dominate this metric.

---

# 3. RMSE (Root Mean Squared Error)

[
RMSE = \sqrt{MSE}
]

RMSE = \sqrt{MSE}

### Your Result

```python
rmse = 65.85
```

### Meaning

Average prediction error magnitude is about **66 units**.

### Why RMSE Matters

RMSE is in the **same unit as the target**, making it easier to interpret.

### Comparison with MAE

```python
MAE  = 62.17
RMSE = 65.85
```

Since RMSE is only slightly larger than MAE:

* errors are relatively consistent,
* you probably do NOT have many huge outliers.

---

# 4. R² Score (Coefficient of Determination)

[
R^2 = 1 - \frac{\sum(y_i-\hat{y}_i)^2}{\sum(y_i-\bar{y})^2}
]

R^2 = 1 - \frac{\sum (y_i-\hat{y}_i)^2}{\sum (y_i-\bar{y})^2}

### Your Result

```python
r2 = -8.05
```

## This is the BIG warning sign.

### R² Interpretation

| R² Value | Meaning                        |
| -------- | ------------------------------ |
| 1.0      | Perfect predictions            |
| 0.0      | Same as predicting the mean    |
| < 0      | Worse than predicting the mean |

Your model:

```python
-8.05
```

means:

> Your Random Forest performs MUCH WORSE than simply predicting the average value every time.

---

# Why Can R² Be So Bad While Accuracy Looks Good?

This often happens when:

## Possible Issue 1: Small target variance

If actual values barely vary:

* even moderate prediction errors destroy R².

---

## Possible Issue 2: Wrong scaling/inverse transform

Very common.

Example:

* y was normalized/log-scaled during training,
* predictions were not inverse-transformed properly before evaluation.

This can completely destroy R².

---

## Possible Issue 3: Time-series shift problems

If this is forecasting:

* predictions may follow trend direction,
* but lag behind actual values.

Then:

* directional accuracy becomes high,
* R² becomes terrible.

---

## Possible Issue 4: Data leakage in directional metric

A `directed_accuracy = 1.0` is suspiciously perfect.

That almost never happens in real forecasting.

You should verify:

* future values are not leaking into features,
* train/test split is chronological,
* no overlap exists.

---

# 5. SMAPE (Symmetric Mean Absolute Percentage Error)

[
SMAPE = \frac{1}{n}\sum \frac{|y_i-\hat{y}_i|}{(|y_i|+|\hat{y}_i|)/2}
]

SMAPE = \frac{1}{n}\sum \frac{|y_i-\hat{y}_i|}{(|y_i|+|\hat{y}_i|)/2}

### Your Result

```python
smape = 0.1667
```

≈ **16.67%**

### Interpretation

Your forecasts are off by about:

```python
16.7%
```

on average relative to magnitude.

### Rule of Thumb

| SMAPE  | Quality   |
| ------ | --------- |
| <10%   | Excellent |
| 10–20% | Good      |
| 20–50% | Moderate  |
| >50%   | Poor      |

So:

```python
16.7% = fairly good
```

---

# 6. Forecast Bias

### Your Result

```python
forecast_bias = -62.17
```

### Meaning

Negative bias means:

> Your model systematically UNDERpredicts.

On average:

```python
Prediction ≈ 62 units too low
```

This is important because:

* the model is not centered correctly,
* predictions are consistently shifted downward.

---

# 7. Accuracy

### Your Result

```python
accuracy = 83.33%
```

This is likely derived from:

```python
100 - SMAPE%
```

Because:

```python
100 - 16.67 ≈ 83.33
```

This is NOT standard regression accuracy.

Regression technically does not have a universal “accuracy” metric like classification.

So interpret this carefully.

---

# 8. Directed Accuracy

### Your Result

```python
directed_accuracy = 1.0
```

Meaning:

* the model correctly predicts whether values go up/down every time.

Example:

* Actual: 100 → 110
* Predicted: 90 → 95
  Direction still correct.

### Interpretation

This suggests:

* trend prediction is excellent,
* magnitude prediction is poor.

Again:

```python
100% directional accuracy is unusually high
```

and worth validating carefully.

---

# Final Diagnosis

Your metrics together suggest:

| Metric            | Interpretation                  |
| ----------------- | ------------------------------- |
| MAE/RMSE          | Moderate numeric error          |
| SMAPE             | Decent relative forecasting     |
| Forecast Bias     | Strong underprediction          |
| Directed Accuracy | Excellent trend prediction      |
| R²                | Extremely poor value prediction |

---

# Most Likely Scenarios

## Scenario A — Forecasting problem

Your model captures:

* trend direction

but misses:

* exact levels/magnitude

---

## Scenario B — Evaluation bug

Especially if:

* scaling/log transforms involved,
* inverse transform forgotten,
* train/test leakage exists.

---

# What You Should Check Next

## 1. Verify inverse scaling

If using:

* StandardScaler
* MinMaxScaler
* log transforms

ensure:

```python
y_pred = scaler.inverse_transform(...)
```

before evaluation.

---

## 2. Plot predictions vs actuals

This usually reveals the issue immediately.

Look for:

* constant offset,
* lagging predictions,
* compressed range,
* underprediction trend.

---

## 3. Compare against baseline

Always compare with:

```python
predict mean(y_train)
```

If baseline beats Random Forest:

* features may not contain predictive signal.

---

## 4. Check train/test split

For time series:

* NEVER shuffle randomly.
* Use chronological split.

---

# Bottom Line

Your Random Forest:

* is probably learning trend direction,
* but failing badly at predicting actual magnitudes,
* and may have systematic underprediction or an evaluation pipeline issue.

The biggest red flag is:

```python
R² = -8.05
```

That should be investigated first.